language: python

python:
 - "2.7"
 - "3.3"
 - "3.4"

before_install:
 # install OpenCL
 - sudo apt-get update -qq
 - sudo apt-get install -qq fglrx opencl-headers

 # install conda
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - conda update conda --yes
 - export TESTENV=testenv$TRAVIS_PYTHON_VERSION

install:
 # install requirements using conda (except for [pyopencl, pyopengl])
 - conda create -n $TESTENV --yes pip python=$TRAVIS_PYTHON_VERSION
 - source activate $TESTENV
 - conda install --yes $(grep -viE 'pyopencl|pyopengl' requirements.txt)

 # install [pyopencl, pyopengl] using pip
 - pip install pyopengl
 - pip install pyopencl

 # print useful info 
 - pwd
 - which pip
 - which conda
 - which python
 - conda list
 - conda info -a
 
 # install tupan
 - pip install .

script:
 - python -m unittest discover

branches:
  only:
    - master
    - dev

notifications:
  email: false

