language: python

python:
 - "2.7"
 - "3.3"
 - "3.4"

before_install:
 # install OpenCL
 - sudo apt-get update -qq
 - sudo apt-get install -qq fglrx opencl-headers

 # install conda
 - pip install conda
 - conda init
 - export TESTENV=$HOME/testenv$TRAVIS_PYTHON_VERSION
 - export PATH=$TESTENV/bin:$PATH

 # print useful info 
 - pwd
 - which pip
 - which conda
 - which python
 - conda list
 - conda info -a
 
install:
 # install requirements using conda (except for [pyopencl, pyopengl])
 - conda create -p $TESTENV --yes pip python=$TRAVIS_PYTHON_VERSION
 - conda install -p $TESTENV --yes $(grep -viE 'pyopencl|pyopengl' requirements.txt)

 # install [pyopencl, pyopengl] using pip
 - pip install pyopengl
 - pip install pyopencl

 # install tupan
 - pip install .

script:
 - python -m unittest discover

branches:
  only:
    - master
    - dev

notifications:
  email: false

