language: python

python:
 - "2.7"
 - "3.3"
 - "3.4"

env:
 - TOX_ENV=test
 - TOX_ENV=docs

before_install:
 # install OpenCL
 - sudo apt-get update -qq
 - sudo apt-get install -qq fglrx opencl-headers

 # install conda
 - sudo pip install conda
 - sudo conda init
 - export TESTENV=$HOME/testenv$TRAVIS_PYTHON_VERSION
 - export PATH=$TESTENV/bin:$PATH
 
install:
 # install requirements using conda (except for [pyopencl, pyopengl])
 - conda create -p $TESTENV --yes pip python=$TRAVIS_PYTHON_VERSION
 - conda install -p $TESTENV --yes $(grep -viE 'pyopencl|pyopengl' requirements.txt)

 # install [pyopencl, pyopengl] using pip
 - pip install pyopengl
 - pip install pyopencl

 # install tox
 - pip install tox

 # print useful info
 - pwd
 - which python
 - which pip
 - which tox
 - which conda
 - conda list
 - conda info -a

script:
 - tox -e $TOX_ENV

branches:
  only:
    - master
    - dev

notifications:
  email: false

