language: python

python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

os:
 - linux

env:
 - CC=gcc
 - CC=clang

matrix:
 allow_failures:
  - env: CC=clang

branches:
 only:
  - master
  - dev

notifications:
 email: false

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.7
   - ubuntu-toolchain-r-test
  packages:
   - gcc-5
   - g++-5
   - clang-3.7
#   - opencl-headers
#   - fglrx-dev

before_install:
 # setup compiler
 - $CC --version
 - if [ "$CC" = "gcc" ]; then export CC="gcc-5" CXX="g++-5"; fi
 - if [ "$CC" = "clang" ]; then export CC="clang-3.7" CXX="clang++-3.7"; fi
 - $CC --version

 # install OpenCL
 - sudo apt-get update -qq
 - sudo apt-get install -qq fglrx-dev opencl-headers

 # install conda
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - conda update --all --yes
 - export TESTENV=testenv$TRAVIS_PYTHON_VERSION

 # install requirements using conda (except for pyopencl)
 - conda create -n $TESTENV --yes python=$TRAVIS_PYTHON_VERSION
 - source activate $TESTENV
 - conda install --yes $(grep -viE 'pyopencl' requirements.txt)
 - conda install --yes pytest

 # install pyopencl using pip
 - pip install pyopencl

 # print useful info
 - pwd
 - conda info -a
 - conda list

install:
 - pip install .

script:
 - py.test -s

