language: python

env:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"

install:
 # install conda
 - sudo pip install conda
 # install deps
 - sudo conda init
 - sudo conda update conda --yes
 - conda create -p $HOME/testenv --yes pip python=$TRAVIS_PYTHON_VERSION
 - export PATH=$HOME/py/testenv:$PATH
 # install deps (except for pyopencl) using conda
 - conda install --yes $(grep -v pyopencl requirements.txt)
 # install pyopencl using pip
 - pip install pyopencl
 # install tupan
 - pip install .

script:
 - python -m unittest discover

branches:
  only:
    - master
    - dev

notifications:
  email: false

#before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq python-cffi
# - sudo apt-get install -qq python-numpy
# - sudo apt-get install -qq python-scipy
# - sudo apt-get install -qq python-h5py
# - sudo apt-get install -qq python-pyopencl
# - sudo apt-get install -qq python-matplotlib
# - sudo apt-get install -qq python-opengl
# - sudo apt-get install -qq python-yaml
# - sudo apt-get install -qq python3-cffi
# - sudo apt-get install -qq python3-numpy
# - sudo apt-get install -qq python3-scipy
# - sudo apt-get install -qq python3-h5py
# - sudo apt-get install -qq python3-pyopencl
# - sudo apt-get install -qq python3-matplotlib
# - sudo apt-get install -qq python3-opengl
# - sudo apt-get install -qq python3-yaml

