language: python

notifications:
  email: false

virtualenv:
  system_site_packages: true

python:
  - "3.3"
  - "3.2"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install -r requirements.txt --use-mirrors"

# command to run tests, e.g. python setup.py test
script:
  - "python -m unittest discover"

