language: python

python:
 - "2.7"
 - "3.3"
 - "3.4"


before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq fglrx opencl-headers

 # install conda
 - sudo pip install conda
 - sudo conda init
 - sudo conda update conda --yes
 
install:
 - export PATH=$HOME/testenv/bin:$PATH

 # install deps using conda
 - conda create -p $HOME/testenv --yes pip python=$TRAVIS_PYTHON_VERSION
 - conda install -p $HOME/testenv --yes $(grep -viE 'pyopencl|pyopengl' requirements.txt)

 # install deps using pip
 - pip install pyopengl
 - pip install pyopencl

 # print useful info
 - which python
 - which pip
 - conda list
 - conda info -a

 # install tupan
 - pip install .

script:
 - python -m unittest discover

branches:
  only:
    - master
    - dev

notifications:
  email: false

