language: python

env:
 - TOXENV=py27
# - TOXENV=py32
# - TOXENV=py33
 - TOXENV=py34
 - TOXENV=docs

before_install:
 - sudo apt-get update -qq
# - sudo apt-get install -qq python-cffi
 - sudo apt-get install -qq python-numpy
 - sudo apt-get install -qq python-scipy
 - sudo apt-get install -qq python-h5py
 - sudo apt-get install -qq python-pyopencl
 - sudo apt-get install -qq python-matplotlib
 - sudo apt-get install -qq python-opengl
 - sudo apt-get install -qq python-yaml
# - sudo apt-get install -qq python3-cffi
# - sudo apt-get install -qq python3-numpy
# - sudo apt-get install -qq python3-scipy
# - sudo apt-get install -qq python3-h5py
# - sudo apt-get install -qq python3-pyopencl
# - sudo apt-get install -qq python3-matplotlib
# - sudo apt-get install -qq python3-opengl
# - sudo apt-get install -qq python3-yaml

install:
- pip install tox
- pip install -r requirements.txt

script:
- tox

branches:
  only:
    - master
    - dev

notifications:
  email: false

