language: python

env:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"


before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq fglrx opencl-headers
 
install:
 # install conda
 - sudo pip install conda
 # install deps
 - sudo conda init
 - sudo conda update conda --yes
 - conda create -p $HOME/testenv --yes pip python=$TRAVIS_PYTHON_VERSION
 - conda install -p $HOME/testenv --yes $(grep -viE 'pyopencl|pyopengl' requirements.txt)
 - export PATH=$HOME/testenv/bin:$PATH
 # install other deps using pip
 - pip install pyopengl
 - pip install pyopencl
 # install tupan
 - pip install .

script:
 - python -m unittest discover

branches:
  only:
    - master
    - dev

notifications:
  email: false

